// Audience-picker hero plates — full-bleed editorial portraits stored
// in the public `wardrobe-basics` bucket under firstfit/. Generated by
// the-edit's src/scripts/firstFitHeroes.ts (Zara SS24 desert lookbook).
//
// Same bucket as wardrobeBasicsPhotos — no second bucket to maintain.

import type { AudienceIdentity } from '@/lib/firstWeek';

const SUPABASE_PUBLIC_BASE =
  'https://bocvtwwmqphfnwmzdjcc.supabase.co/storage/v1/object/public/wardrobe-basics';

const SLUG: Record<AudienceIdentity, string> = {
  man: 'man',
  woman: 'woman',
  'non-binary': 'non-binary',
};

export function getFirstFitHeroUrl(identity: AudienceIdentity): string {
  return `${SUPABASE_PUBLIC_BASE}/firstfit/${SLUG[identity]}.png`;
}

export const AUDIENCE_ORDER: readonly AudienceIdentity[] = ['man', 'woman', 'non-binary'];

export const AUDIENCE_CAPTIONS: Record<AudienceIdentity, string> = {
  man: 'tees, denim, leather. cut from that rail.',
  woman: 'slips, knits, tailoring. cut from that rail.',
  'non-binary': 'the full rail. nothing held back.',
};
